.\"
.TH 7zz "1" "June 2021" "21.02"
.SH NAME
7zz \- 7-Zip file archiver with a high compression ratio
.SH DESCRIPTION
7-Zip file archiver with a high compression ratio
.SH SEE ALSO
.BR https://www.7-zip.org/
.SH COPYRIGHT
Copyright \(co 1999\-2021 Igor Pavlov.
.br
Distributed under the LGPL-2.1+ license.
