#!/bin/sh

set -eu

uscan_out=$(uscan --safe --force-download --verbose | grep -e 'Successfully downloaded package' -e 'Not downloading, using existing file')
szipball=$(echo "$uscan_out" | grep "\-src\.7z" | sed 's/^.*\(7z.*\-src\.7z\).*$/\1/')
tarball_base=$(echo "$szipball" | sed 's/\.7z//')

d=$(mktemp -d)

7z x -o"${d}" ../${szipball}

unset POSIXLY_CORRECT
tar --sort=name \
    --mtime="@${SOURCE_DATE_EPOCH:-$(dpkg-parsechangelog -STimestamp)}" \
    --owner=0 --group=0 --numeric-owner \
    --pax-option=exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime \
    --directory="${d}" --xz -cf ../${tarball_base}.tar.xz .

mk-origtargz ../${tarball_base}.tar.xz

rm -rf "${d}"
